name: Build Canary

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install and Build
      working-directory: MaiChartManager/Front
      run: |
        pnpm install
        pnpm build

    - name: Upload wwwroot
      uses: actions/upload-artifact@v4
      with:
        name: wwwroot
        path: MaiChartManager/wwwroot

  build:
    name: Build
    runs-on: windows-latest
    needs: build-frontend
    
    steps:
    - run: git config --global core.longPaths true
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Checkout Assets
      uses: clansty/checkout@main
      with:
        repository: MuNET-OSS/AquaMai-Build-Assets
        token: ${{ secrets.BUILD_ASSETS_PAT }}
        path: build-assets
        max-attempts: 50
        min-retry-interval: 1
        max-retry-interval: 5

    - name: Copy Assets
      shell: powershell
      run: |
        Write-Host "Copying assets..."
        Copy-Item -Path "build-assets/SDEZ/*" -Destination "AquaMai/Libs/" -Recurse -Force

    - name: Setup Nuget
      shell: powershell
      run: |
        dotnet nuget list source
        if (-not (dotnet nuget list source | Select-String "nuget.org")) {
            dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
        }

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Download wwwroot
      uses: actions/download-artifact@v4
      with:
        name: wwwroot
        path: MaiChartManager/wwwroot

    - name: Publish self-contained exe
      shell: powershell
      run: |
        dotnet publish .\MaiChartManager\MaiChartManager.csproj `
          -c Crack `
          -r win-x64 `
          --self-contained true `
          -o .\artifacts\publish\MaiChartManager-win-x64

    - name: Upload exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: MaiChartManager-win-x64-exe
        path: artifacts/publish/MaiChartManager-win-x64
